<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="22" started-at="2019-04-29T22:35:07Z" finished-at="2019-04-29T22:35:07Z">
    <groups>
      <group name="testEntityKey:EXE-TC-2">
        <method signature="ProgramTest.IsOver16()[pri:0, instance:ph.smoke.ProgramTest@7dc7cbad]" name="IsOver16" class="ph.smoke.ProgramTest"/>
        <method signature="ProgramTest.createMessageTest()[pri:0, instance:ph.smoke.ProgramTest@7dc7cbad]" name="createMessageTest" class="ph.smoke.ProgramTest"/>
        <method signature="ProgramTest.testConcat()[pri:0, instance:ph.smoke.ProgramTest@7dc7cbad]" name="testConcat" class="ph.smoke.ProgramTest"/>
      </group> <!-- testEntityKey:EXE-TC-2 -->
      <group name="testEntityKey:EXE-TC-1">
        <method signature="CalculatorTest.testDivison()[pri:0, instance:ph.smoke.CalculatorTest@3a82f6ef]" name="testDivison" class="ph.smoke.CalculatorTest"/>
        <method signature="CalculatorTest.testSum()[pri:0, instance:ph.smoke.CalculatorTest@3a82f6ef]" name="testSum" class="ph.smoke.CalculatorTest"/>
      </group> <!-- testEntityKey:EXE-TC-1 -->
      <group name="requirementEntityKey:EXE-RQ-1">
        <method signature="CalculatorTest.testDivison()[pri:0, instance:ph.smoke.CalculatorTest@3a82f6ef]" name="testDivison" class="ph.smoke.CalculatorTest"/>
        <method signature="CalculatorTest.testSum()[pri:0, instance:ph.smoke.CalculatorTest@3a82f6ef]" name="testSum" class="ph.smoke.CalculatorTest"/>
        <method signature="ProgramTest.IsOver16()[pri:0, instance:ph.smoke.ProgramTest@7dc7cbad]" name="IsOver16" class="ph.smoke.ProgramTest"/>
        <method signature="ProgramTest.createMessageTest()[pri:0, instance:ph.smoke.ProgramTest@7dc7cbad]" name="createMessageTest" class="ph.smoke.ProgramTest"/>
        <method signature="ProgramTest.testConcat()[pri:0, instance:ph.smoke.ProgramTest@7dc7cbad]" name="testConcat" class="ph.smoke.ProgramTest"/>
      </group> <!-- requirementEntityKey:EXE-RQ-1 -->
    </groups>
    <test name="Default test" duration-ms="22" started-at="2019-04-29T22:35:07Z" finished-at="2019-04-29T22:35:07Z">
      <class name="ph.smoke.CalculatorTest">
        <test-method status="PASS" signature="beforeEachTest()[pri:0, instance:ph.smoke.CalculatorTest@3a82f6ef]" name="beforeEachTest" is-config="true" duration-ms="4" started-at="2019-04-29T23:35:07Z" finished-at="2019-04-29T23:35:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeEachTest -->
        <test-method status="PASS" signature="initCalculator()[pri:0, instance:ph.smoke.CalculatorTest@3a82f6ef]" name="initCalculator" is-config="true" duration-ms="0" started-at="2019-04-29T23:35:07Z" finished-at="2019-04-29T23:35:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initCalculator -->
        <test-method status="PASS" signature="testDivison()[pri:0, instance:ph.smoke.CalculatorTest@3a82f6ef]" name="testDivison" duration-ms="4" started-at="2019-04-29T23:35:07Z" finished-at="2019-04-29T23:35:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDivison -->
        <test-method status="PASS" signature="testSum()[pri:0, instance:ph.smoke.CalculatorTest@3a82f6ef]" name="testSum" duration-ms="0" started-at="2019-04-29T23:35:07Z" finished-at="2019-04-29T23:35:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSum -->
        <test-method status="PASS" signature="afterEachTest()[pri:0, instance:ph.smoke.CalculatorTest@3a82f6ef]" name="afterEachTest" is-config="true" duration-ms="0" started-at="2019-04-29T23:35:07Z" finished-at="2019-04-29T23:35:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterEachTest -->
      </class> <!-- ph.smoke.CalculatorTest -->
      <class name="ph.smoke.ProgramTest">
        <test-method status="PASS" signature="IsOver16()[pri:0, instance:ph.smoke.ProgramTest@7dc7cbad]" name="IsOver16" duration-ms="2" started-at="2019-04-29T23:35:07Z" finished-at="2019-04-29T23:35:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- IsOver16 -->
        <test-method status="FAIL" signature="createMessageTest()[pri:0, instance:ph.smoke.ProgramTest@7dc7cbad]" name="createMessageTest" duration-ms="1" started-at="2019-04-29T23:35:07Z" finished-at="2019-04-29T23:35:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Hello World] but found [Hello World ]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Hello World] but found [Hello World ]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at ph.smoke.ProgramTest.createMessageTest(ProgramTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createMessageTest -->
        <test-method status="FAIL" signature="testConcat()[pri:0, instance:ph.smoke.ProgramTest@7dc7cbad]" name="testConcat" duration-ms="1" started-at="2019-04-29T23:35:07Z" finished-at="2019-04-29T23:35:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Hello World] but found [HelloWorld]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Hello World] but found [HelloWorld]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at ph.smoke.ProgramTest.testConcat(ProgramTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testConcat -->
      </class> <!-- ph.smoke.ProgramTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
